### PR TITLE
Dockerized API for easier onboarding and deployment

### PR DESCRIPTION
**Pull request by syousif94**
I dockerized the API and its dependencies so the api can run anywhere with one command. I also updated the readme with the relevant instructions.

I'm not familiar with rails development, so I think the docker cluster has to be restarted every time the source is updated. If there's a traditional rails way of restarting the api when the source code changes, please let me know and I'll add it to the docker environment.

You can also continue building the API without installing Docker.

### CODE REVIEW

**Comment by bkerley** [comment]
Trying this, I get an error:
```
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Fetching source index from https://rubygems.org/
Could not verify the SSL certificate for https://rubygems.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most
likely your system doesn't have the CA certificates needed for verification. For
information about OpenSSL certificates, see bit.ly/ruby-ssl. To connect without
using SSL, edit your Gemfile sources and change 'https' to 'http'.
```

> I'm not familiar with rails development, so I think the docker cluster has to be restarted every time the source is updated. If there's a traditional rails way of restarting the api when the source code changes, please let me know and I'll add it to the docker environment.

In Rails development mode, 90% of what gets worked on in development (the `app` directory, `config/routes.rb`) is live-reloaded, so as long as the volume is mounted and not copied over it should be fine.

**Comment by syousif94** [comment]
I can't seem to recreate the error. Do you have any proxy settings set for docker?

**Comment by bkerley** [comment]
```diff
diff --git a/Dockerfile b/Dockerfile
index b3f815e..5f46a9a 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -7,4 +7,5 @@ ADD Gemfile /home/app/Gemfile
 ADD Gemfile.lock /home/app/Gemfile.lock
 
 RUN apk update && apk --update add ruby-irb ruby-rake ruby-bigdecimal libstdc++ build-base libffi-dev \
+  && update-ca-certificates \
   && bundle install
```

I had to do this to make the `docker-compose up` step work. Once I did that, `docker-compose down`, `docker-compose rm`, and `docker-compose up` worked.

**Comment by syousif94** [comment]
Cool, updated the pull request.

**Comment by bkerley** [comment]
What version of alpine does `centurylink/alpine-rails` pull from? If it's just `latest` that might cause this, as docker is loath to update those sometimes.

**Comment by syousif94** [comment]
Looks like 3.2 😕

**Pull request merged**
